const { chromium } = require("playwright-core");
const BASE = "http://localhost:3099";
const OUT = __dirname + "/shots/";
const hide = "nextjs-portal{display:none!important}";
async function shot(page, name, full = false) { await page.addStyleTag({ content: hide }); await page.screenshot({ path: OUT + name + ".png", fullPage: full }); console.log("saved", name); }
async function scrollThrough(page) { await page.evaluate(async () => { for (let y = 0; y < document.body.scrollHeight; y += 500) { window.scrollTo(0, y); await new Promise(r => setTimeout(r, 120)); } window.scrollTo(0, 0); }); await page.waitForTimeout(1500); }
(async () => {
  const browser = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
  const mob = await browser.newContext({ bypassCSP: true, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const desk = await browser.newContext({ bypassCSP: true, viewport: { width: 1440, height: 900 } });
  let p;
  const step = async (label, fn) => { try { await fn(); } catch (e) { console.log("FAIL", label, e.message.slice(0, 200)); } };

  await step("menu", async () => { p = await mob.newPage(); await p.goto(BASE + "/prices", { waitUntil: "networkidle" }); await p.click("button:has-text('Open main menu')"); await p.waitForTimeout(600); await shot(p, "menu-open-mobile"); await p.close(); });
  await step("prices filters mobile", async () => { p = await mob.newPage(); await p.goto(BASE + "/prices", { waitUntil: "networkidle" }); await p.click("text=Filters"); await p.waitForTimeout(600); await shot(p, "prices-filters-open-mobile"); await p.close(); });
  await step("prices flat desktop", async () => { p = await desk.newPage(); await p.goto(BASE + "/prices", { waitUntil: "networkidle" }); await p.click("button:has-text('Flat')"); await p.waitForTimeout(800); await scrollThrough(p); await shot(p, "prices-flat-desktop"); await p.close(); });
  await step("prices full chart", async () => { p = await desk.newPage(); await p.goto(BASE + "/prices", { waitUntil: "networkidle" }); await p.waitForTimeout(1500); await p.click("button:has-text('Show full chart')"); await p.waitForTimeout(2500); await shot(p, "prices-fullchart-desktop"); await p.close(); });
  await step("prices search", async () => { p = await desk.newPage(); await p.goto(BASE + "/prices?q=zzzz", { waitUntil: "networkidle" }); await p.waitForTimeout(1500); await shot(p, "prices-search-empty-desktop"); await p.close(); });
  await step("home scrolled", async () => { p = await desk.newPage(); await p.goto(BASE + "/", { waitUntil: "networkidle" }); await scrollThrough(p); await shot(p, "home-loaded-desktop", true); await p.close(); });
  await step("market all cols", async () => { p = await desk.newPage(); await p.goto(BASE + "/market", { waitUntil: "networkidle" }); await p.click("button:has-text('Show all columns')"); await p.waitForTimeout(800); await p.click("th:has-text('1M')"); await p.waitForTimeout(800); await scrollThrough(p); await shot(p, "market-allcols-sorted-desktop"); await p.close(); });
  await step("market chart row", async () => { p = await desk.newPage(); await p.goto(BASE + "/market", { waitUntil: "networkidle" }); await p.locator("button:has-text('Show')").nth(1).click(); await p.waitForTimeout(2500); await shot(p, "market-row-chart-desktop"); await p.close(); });
  await step("market mobile scrolled right", async () => { p = await mob.newPage(); await p.goto(BASE + "/market", { waitUntil: "networkidle" }); await p.evaluate(() => { const t = document.querySelector("table"); let el = t; while (el && el.scrollWidth <= el.clientWidth) el = el.parentElement; if (el) el.scrollLeft = 400; window.scrollTo(0, 600); }); await p.waitForTimeout(800); await shot(p, "market-mobile-scrolled"); await p.close(); });
  await step("product 1Y hover", async () => { p = await desk.newPage(); await p.goto(BASE + "/product/110", { waitUntil: "networkidle" }); await p.click("button:has-text('1Y')"); await p.waitForTimeout(1500); const c = await p.locator(".recharts-surface").first().boundingBox(); if (c) await p.mouse.move(c.x + c.width * 0.6, c.y + c.height * 0.5); await p.waitForTimeout(800); await p.evaluate(() => window.scrollTo(0, 700)); await p.waitForTimeout(300); if (c) await p.mouse.move(c.x + c.width * 0.6, c.y + c.height * 0.5 - 700); await p.waitForTimeout(800); await shot(p, "product-1y-hover-desktop"); await p.close(); });
  await step("product stale", async () => { p = await desk.newPage(); await p.goto(BASE + "/product/105", { waitUntil: "networkidle" }); await p.waitForTimeout(1000); await shot(p, "product-stale-desktop"); await p.close(); });
  await step("boxcalc filled", async () => { p = await desk.newPage(); await p.goto(BASE + "/box-calculator", { waitUntil: "networkidle" }); await p.waitForTimeout(1500); const sel = p.locator("select").first(); const opts = await sel.locator("option").allTextContents(); console.log("set options", opts.slice(0, 5)); await sel.selectOption({ index: 1 }); await p.locator("input[type=number]").first().fill("6"); await p.click("button:has-text('Add Packs')"); await p.waitForTimeout(500); const inputs = p.locator("input[placeholder*='0.00']"); const n = await inputs.count(); if (n >= 2) { await inputs.nth(0).fill("8"); await inputs.nth(1).fill("49.99"); } await p.waitForTimeout(1000); await shot(p, "boxcalc-filled-desktop", true); await p.close(); });
  await step("compare csv", async () => { p = await desk.newPage(); await p.goto(BASE + "/compare", { waitUntil: "networkidle" }); await p.waitForTimeout(1500); await p.setInputFiles("input[type=file]", __dirname + "/shop.csv"); await p.waitForTimeout(1500); await shot(p, "compare-csv-desktop", true); await p.close(); });
  await step("compare csv mobile", async () => { p = await mob.newPage(); await p.goto(BASE + "/compare", { waitUntil: "networkidle" }); await p.waitForTimeout(1500); await p.setInputFiles("input[type=file]", __dirname + "/shop.csv"); await p.waitForTimeout(1500); await p.evaluate(() => window.scrollTo(0, 1300)); await shot(p, "compare-csv-mobile"); await p.close(); });
  await step("login error", async () => { p = await desk.newPage(); await p.goto(BASE + "/auth/login", { waitUntil: "networkidle" }); await p.fill("input[type=email]", "a@b.co"); await p.fill("input[type=password]", "wrongpass"); await p.waitForTimeout(300); await shot(p, "login-filled-desktop"); await p.close(); });
  await browser.close();
})();
