"use client";

import { useState } from "react";
import Image from "next/image";

interface ProductImageProps {
  imageUrl?: string | null;
  productName: string;
  className?: string;
  /**
   * Render the small WebP derivative instead of the full-size original.
   * Set this wherever the image paints into a list-sized box — the originals
   * are ~743x1000 / ~91 KB and were being downloaded whole for 24-56px
   * thumbnails. Falls back to the original automatically if no derivative
   * exists yet for this product.
   */
  preferThumbnail?: boolean;
}

// Mirror of thumbnail_object_path() in main.py: products/{id}.{ext} ->
// products/{id}_thumb.webp. Keep both sides in sync.
function toThumbnailUrl(url: string): string | null {
  const match = url.match(/^(.*\/products\/)([^/]+)\.(?:jpg|jpeg|png|webp)$/i);
  if (!match) return null;
  return `${match[1]}${match[2]}_thumb.webp`;
}

/**
 * Product image component with loading state and error fallback
 *
 * @param imageUrl - URL of the product image
 * @param productName - Name of the product (used for alt text)
 * @param className - Additional CSS classes for the container
 */
export default function ProductImage({
  imageUrl,
  productName,
  className = "",
  preferThumbnail = false,
}: ProductImageProps) {
  const [imageError, setImageError] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  // Thumbnails are generated by the scraper, so a product scraped before that
  // shipped has none. Rather than gate on a DB column, try the derivative and
  // fall back to the original on the first error: thumb -> original -> "no
  // image" placeholder.
  const [thumbnailFailed, setThumbnailFailed] = useState(false);

  const thumbnailUrl =
    preferThumbnail && imageUrl && !thumbnailFailed
      ? toThumbnailUrl(imageUrl)
      : null;

  const handleImageLoad = () => {
    setIsLoading(false);
  };

  const handleImageError = () => {
    if (thumbnailUrl) {
      // Derivative missing — retry with the original before giving up.
      setThumbnailFailed(true);
      return;
    }
    setImageError(true);
    setIsLoading(false);
  };

  // Fallback UI when no image or error
  if (!imageUrl || imageError) {
    return (
      <div
        className={`bg-slate-200 border-2 border-dashed border-slate-300 flex items-center justify-center ${className}`}
      >
        <div className="text-center text-slate-500 p-4">
          <div className="text-2xl mb-2">🃏</div>
          <div className="text-xs font-medium">No Image</div>
        </div>
      </div>
    );
  }

  // imageUrl is narrowed to string by the guard above.
  const resolvedUrl = thumbnailUrl ?? imageUrl;

  return (
    <div className={`relative overflow-hidden bg-white ${className}`}>
      {isLoading && (
        <div className="absolute inset-0 bg-slate-200 animate-pulse flex items-center justify-center">
          <div className="text-slate-400">Loading...</div>
        </div>
      )}
      <div className="w-full h-full flex items-center justify-center p-4">
        <Image
          key={resolvedUrl}
          src={resolvedUrl}
          alt={productName}
          width={200}
          height={200}
          className={`max-w-full max-h-full object-contain transition-opacity ${
            isLoading ? "opacity-0" : "opacity-100"
          }`}
          onLoad={handleImageLoad}
          onError={handleImageError}
          loading="lazy"
          unoptimized
        />
      </div>
    </div>
  );
}
